

name: "Terraform-Plan-Apply-Infra-Release"


on:
  push:
    branches: 
      - main 
defaults:
  run:
   shell: bash
   working-directory: infrasetup
jobs:
  terraform:
    name:    ${{matrix.runner}} - {{matrix.environment}}
    runs-on: [ '${{matrix.runner}}']
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: dev1
            runner: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_AVAILABILITY_ZONE: ${{secrets.AWS_AVAILABILITY_ZONE}}'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve